---
- name: Add Portainer stack template
  template:
    src: portainer_stack.yaml.j2
    dest: "{{ docker_stack_dir }}/portainer_stack.yaml"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Spin up docker stack
  docker_stack:
    state: present
    name: portainer
    compose:
      - "{{ docker_stack_dir }}/portainer_stack.yaml"