---
- hosts: gcp_test
  become: true
  roles:
    - prereqs
    - docker
    - dockerswarm
    - portainer_swarm
    - traefik_swarm
    - role: jenkins_swarm
      vars:
        jenkins_url: jenkins.35.193.154.225.nip.io