---
- hosts: gcp_test
  become: true
  roles:
    - prereqs
    - docker
    - dockerswarm
    - portainer_swarm
    - traefik_swarm
    - role: jenkins_swarm
      vars:
        jenkins_url: jenkins.34.69.158.223.nip.io