---
- include: ubuntu18.yaml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'

- include: ubuntu20.yaml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'focal'