---
- name: Ensure Docker group exists
  group:
    name: docker
    state: present

- name: Add User to Docker Group
  user:
    append: yes
    groups: docker
    name: "{{ lookup('env','USER') }}"

- debug:
    msg: Restart system for group changes to take affect